### ISSUE TITLE
[$20] Layout Issue in the Chat Room

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#429] opened 2015-01-23 05:12 UTC
Description
-----------------------------------------------------------------
Layout Issue in the Chat Room

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Chat Room'

Check the bottom border

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Chat room bottom border must fix

Actual Result
-----------------------------------------------------------------
Layout Issue in the Chat Room

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![2](https://cloud.githubusercontent.com/assets/4592712/5870143/89dbb506-a2ec-11e4-9dce-c7ea2bdd9707.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment] 2015-02-05 11:36
working on it

**Comment by huangqun** [comment] 2015-02-07 06:19
@shubhendusaurabh actually I'm not able to reproduce it, it looks fine. But after applying your fix it looks like this:

![image](https://cloud.githubusercontent.com/assets/6045894/6091077/5990d7ac-aed4-11e4-9eed-2003f1a1904b.png)

**Comment by shubhendusaurabh** [comment] 2015-02-09 18:32
@huangqun i can reproduce this on chrome v40 only but not on firefox.

**Comment by huangqun** [comment] 2015-02-10 03:29
@shubhendusaurabh Are you on windows or mac? I tested on Chrome v40 on Mac and can't reproduce it.

**Comment by shubhendusaurabh** [comment] 2015-02-10 06:24
@huangqun i am using Linux Mint 17. this is what i see in chrome
![chatroom](https://cloud.githubusercontent.com/assets/1818387/6122568/946f35b4-b11b-11e4-965f-6982cdb29b09.png)

**Comment by huangqun** [comment] 2015-02-13 05:28
can't reproduce this on most browsers so I'm closing this.

**Closed by huangqun** 2015-02-13 05:28 UTC
Labels: fix me
