### ISSUE TITLE
[$25] Need to click twice to clear the code

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#474] opened 2015-01-23 15:03 UTC
Description
-----------------------------------------------------------------
Need to click twice to clear the code

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
Register for a contest
Once the coding phase starts, click Enter
From the problems list given in right sidebar click the link "Unopened"
Enter your code in coding area
Click Compile
Now click Submit and click Yes on the confirmation window
Click Back to match

Now open the same Problem again
Click Clear from the code area

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must clear the code in single attempt

Actual Result
-----------------------------------------------------------------
Need to click twice to clear the code

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 40.0.2214.91 m and FF 34.0.5 in Windows 7 Pro 64bit

Video
-----------------------------------------------------------------
https://drive.google.com/open?id=0B2TRwlgOU4zmcTBJNWpXRUhxdDQ&authuser=0

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by ananthhh** [comment] 2015-02-04 06:18
Not able to reproduce. I think its already fixed

**Comment by huangqun** [comment] 2015-02-05 04:17
I cannot reproduce it either, marking as fixed.

**Closed by huangqun** 2015-02-05 04:17 UTC
Labels: fix me
