### ISSUE TITLE
[$30] 'Back to My Room' won't do nothing when the user is not registered for that event

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#325] opened 2014-12-16 00:43 UTC
Description
-----------------------------------------------------------------
'Back to My Room' won't do nothing when the user is not registered for that event

Steps
-----------------------------------------------------------------
Go to https://qa.arena.topcoder.com/#/a/home
Login as valid user
Don't register
Wait till the contest completed
Click ENTER

CLick 'Back to My Room' button

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must show info message/validation

Actual Result
-----------------------------------------------------------------
'Back to My Room' won't do nothing when the user is not registered for that event

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![39](https://cloud.githubusercontent.com/assets/4592712/5446841/71188302-84ea-11e4-88da-4c02e767031a.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by GSTVAC** [comment] 2015-01-03 17:38
working

**Comment by GSTVAC** [comment] 2015-01-03 19:55
I can't reproduce it.

**Comment by huangqun** [comment] 2015-01-04 04:58
@GSTVAC so do you see a info message / validation?

**Comment by GSTVAC** [comment] 2015-01-04 12:17
No. I can't see the button.

**Comment by huangqun** [comment] 2015-01-04 12:45
OK, that seems to be the same case for me. Closing this.

**Closed by huangqun** 2015-01-04 12:45 UTC
Labels: fix me
