### ISSUE TITLE
[$20] [Common] Layout Issue when we scroll the page while the Filter is activated

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#122] opened 2014-12-11 21:30 UTC
_From @sdgun on October 20, 2014 19:30_

Description
-----------------------------------------------------------------
[Common] Layout Issue when we scroll the page while the Filter is activated

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Open a completed Contest (Click ENTER)
Click 'Challenges & Leaderboard '
Click Filter in 'Challengers', 'Challenges' or 'Room  Leaderboard'
In Expand Mode also
Scroll the page up

Expected Result
-----------------------------------------------------------------
Must fix the Issue, 

Actual Result
-----------------------------------------------------------------
Layout Issue when we scroll the page while the Filter is activated

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7

Image
-----------------------------------------------------------------
![22](https://cloud.githubusercontent.com/assets/4592712/4709365/b2d2a0f2-589e-11e4-849e-910f2b4abd46.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201410 Release

_Copied from original issue: cloudspokes/arena-web#866_

**Comment by GSTVAC** [comment] 2015-01-02 00:16
working

**Comment by GSTVAC** [comment] 2015-01-02 18:12
done

**Comment by huangqun** [comment] 2015-01-04 04:51
@GSTVAC again I cannot reproduce this, I'm using Chrome and Firefox on Chrome, could you let me know how to reproduce it?

**Comment by GSTVAC** [comment] 2015-01-04 16:53
@huangqun I'm using Firefox 34.0.5 and Chrome 39.0.2171.95 on Windows 7 Home Premium 64-bits.
commit 14081c9d924a93077f603d189693c5744af5f31c

**Comment by huangqun** [comment] 2015-01-07 04:58
@GSTVAC OK, please submit your fix for this. I will try to test this on Windows 7 instead. Maybe it works on Mac but not on Windows 7. Make sure you use the latest commit from the branch.

**Comment by GSTVAC** [comment] 2015-01-07 22:41
@huangqun #397

**Comment by huangqun** [comment] 2015-01-08 04:03
fixed

**Closed by huangqun** 2015-01-08 04:03 UTC
Labels: fix me
