### ISSUE TITLE
New/Viewed/Solved status freezes at New

### ISSUE THREAD

**Issue by b0w1d** [appirio-tech/arena-web#734] opened 2017-06-08 12:07 UTC
Regardless of having viewed and solved ( passed system tests ), when searching via "Practice Problems", the status remains "New".

**Comment by ssehoony** [comment] 2017-06-28 01:03
This bug happen to me, too.

**Comment by Stevenchen77** [comment] 2017-06-28 21:27
same bug

**Comment by Anton-Velikodnyy** [comment] 2017-08-04 20:20
Same thing here

**Comment by square1001** [comment] 2017-08-17 02:42
Duplicate of #717

**Comment by serge-alexandre** [comment] 2020-06-11 15:04
same here

**Closed** 2020-06-19 07:39 UTC
