### ISSUE TITLE
My Points are not shown in my dashboard

### ISSUE THREAD

**Issue by Shrutichhatbar** [appirio-tech/arena-web#696] opened 2016-10-12 00:34 UTC

**Comment by Shrutichhatbar** [comment] 2016-10-12 00:56
I submitted the code it shows I scored x points but my I check dashboard My Points column is empty

**Comment by jeffswt** [comment] 2016-11-09 14:11
I think you are not submitting it in the contests. But the issue also applies to me.

**Comment by jeffswt** [comment] 2016-11-09 14:21
Duplicate issue with #687.

**Comment by square1001** [comment] 2017-08-17 03:07
Duplicate of #624 
Please close this issue because duplicated one is not very helpful.

**Closed** 2017-08-17 04:44 UTC
