### ISSUE TITLE
[$25] 'Problem Statement' have a horizontal scroll bars

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#456] opened 2015-01-23 07:29 UTC
Description
-----------------------------------------------------------------
'Problem Statement' have a horizontal scroll bars

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the voding phase starts
Click ENTER

Open a Problem
Check the horizontal scroll bars

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must not have horizontal scroll bars in 'Problem Statement'

Actual Result
-----------------------------------------------------------------
'Problem Statement' have a horizontal scroll bars

Environment
-----------------------------------------------------------------
IE 11 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![30](https://cloud.githubusercontent.com/assets/4592712/5871208/9e6d2bea-a2ff-11e4-8b83-086a5b73d11f.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by ananthhh** [comment] 2015-02-04 06:32
Which problem it is? I have checked all problems in Formal SRM and there is no horizontal scrollbar in any of it

**Comment by huangqun** [comment] 2015-02-05 04:37
@sdgun Could you please provide more details on this one? How can we reproduce it?

**Comment by sdgun** [comment] 2015-02-05 04:52
@huangqun, I tried to login to the https://arena.topcoder.com/#/a/home, but it displayed 'Login time out. Please try again at later time.' This is the URL I have used during the competition. How can I login to the web arena now

**Comment by huangqun** [comment] 2015-02-07 04:52
@sdgun It seems to be working now, could you please try again?

**Comment by sdgun** [comment] 2015-02-07 14:49
@huangqun, Same Issue, when I try to login via previous credentials used in the Bug Hunt. It displays 'Invalid username or password. Please try again'. Can I get a common user account that can be used to test this?

**Comment by huangqun** [comment] 2015-02-08 15:46
@sdgun if you are testing on https://arena.topcoder.com/#/a/home you should use your own credentials to login. This is the production site.

**Comment by sdgun** [comment] 2015-02-09 02:15
@huangqun, I have seen this issue in the 'GooseInZooDivTwo' and 'GooseInZooDivOne' problems in IE. This moment I can't see any active matches so that I have checked it with the 'Practice Problems' area because they have the same functionality.

I think the horizontal scroll bar appears in IE because of the Example 3 data in the 'Problem Area'. In IE content is not break into paragraphs, but in Chrome it is 10 line paragraph.

Please check the screen shots.

NOTE: But I can't find the horizontal scroll bar now.

IE
![ie](https://cloud.githubusercontent.com/assets/4592712/6100074/3f7622b8-b02e-11e4-8c22-d21a6eef04ba.png)
Chrome
![chrome](https://cloud.githubusercontent.com/assets/4592712/6100075/3fb0b860-b02e-11e4-83bd-b66d9ceb535f.png)

**Comment by huangqun** [comment] 2015-02-09 10:30
@sdgun So I assume you were saying this can no longer be reproduced right? This might have been fixed already then.

**Comment by sdgun** [comment] 2015-02-09 10:33
@huangqun, Yes. Scroll bar won't display anymore. but the Paragraph issue is there.

**Comment by huangqun** [comment] 2015-02-09 10:36
@sdgun that needs to be reported as a separate issue, and maybe it's already fixed in latest dev branch as well. :)

**Comment by huangqun** [comment] 2015-02-13 05:27
marking this as fixed.

**Closed by huangqun** 2015-02-13 05:27 UTC
Labels: fix me
