### ISSUE TITLE
[$40] Can't expand the 'Problem Area' using mouse fully

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#321] opened 2014-12-15 08:59 UTC
Description
-----------------------------------------------------------------
Can't expand the 'Problem Area' using mouse fully

Steps
-----------------------------------------------------------------
Go to https://qa.arena.topcoder.com/#/a/home
Login as valid user
When the contest starts
Click ENTER

Click on a Problem
Enter code and compile
Click Submit
When the Challenge Phase is ON
Click on another competitors score from Leaderboard
Expand the 'Problem Area' using mouse

NOTE: Same in the Coding phase

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must able to expand the 'Problem Area' using mouse
- Must not display the part of the Coding area when fully expanded

Actual Result
-----------------------------------------------------------------
Can't expand the 'Problem Area' using mouse fully

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![36](https://cloud.githubusercontent.com/assets/4592712/5432841/bd649e00-8466-11e4-8245-764e90d1f770.png)

Video
-----------------------------------------------------------------
https://drive.google.com/open?id=0B2TRwlgOU4zmSmcyZ1ZOYUJCZVE&authuser=0

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by GSTVAC** [comment] 2015-01-02 22:50
working

**Comment by GSTVAC** [comment] 2015-01-03 14:11
done

**Comment by GSTVAC** [comment] 2015-01-08 23:55
@huangqun I didn't understand it. The screencast doesn't show the bottom area of the page, where the problem is.

**Comment by huangqun** [comment] 2015-01-09 02:07
@GSTVAC the problem is after I expanded the 'Problem Area' using mouse, there's no way to bring back the coding area back using mouse?

**Comment by GSTVAC** [comment] 2015-01-10 13:03
@huangqun Yes, there is. In your test the clicking area was too close to the bottom border of the browser, and got overlapped by it. Please, just scroll down the page and you'll see it's working fine.

**Comment by huangqun** [comment] 2015-01-10 13:51
@GSTVAC the pull request https://github.com/appirio-tech/arena-web/pull/412 can no longer be merged due to recent updates to the branch. Can you send a new one?

**Comment by GSTVAC** [comment] 2015-01-10 16:10
@huangqun There's a commit (ab55ecd321ab7c5e95ad11c11389af9b96ab15fb) made by @Helstein that implements the same fix I'm working here. What should I do? Can I overwrite the code?

**Comment by huangqun** [comment] 2015-01-11 03:15
@GSTVAC if that's already fixed by @Helstein then we don't want to overwrite it. But if that's case we can still pay your for verifying the fix, let me know if that's the case so that I know if I should just close this one.

**Comment by GSTVAC** [comment] 2015-01-11 13:18
@huangqun Yes, it's fixed.
________________________________
De: huangqun<mailto:notifications@github.com>
Enviada em: ‎11/‎01/‎2015 01:15
Para: appirio-tech/arena-web<mailto:arena-web@noreply.github.com>
Cc: Gustavo Alves Costa<mailto:gstvac@hotmail.com>
Assunto: Re: [arena-web] [$40] Can't expand the 'Problem Area' using mouse fully (#321)

@GSTVAC if that's already fixed by @Helstein then we don't want to overwrite it. But if that's case we can still pay your for verifying the fix, let me know if that's the case so that I know if I should just close this one.

---

**Comment by huangqun** [comment] 2015-01-13 02:17
fixed

**Closed by huangqun** 2015-01-13 02:17 UTC
Labels: fix me
