### ISSUE TITLE
[$25] Coder info: Not able to scroll till the end

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/arena-web#478] opened 2015-01-23 15:45 UTC
![arenaweb-478](https://cloud.githubusercontent.com/assets/5114190/5877358/00018802-a345-11e4-829c-4574771ce400.jpg)
Env: Mac OS 10.10.1 Chrome39

Go to arena.topcoder.com and login with valid credentials.
Register for an SRM contest and enter into it
Click on the username: magrathean and observe the coder info popup

Actual:
It displays a last line which is not fully visible. Please see the screenshot below. User is also not able to scroll till the end.

Expected:

Info should be fully visible or user should be able to scroll in order to the full information.

**Comment by nithyaasworld** [comment] 2015-01-23 18:17
This also happens with most of the coder info of the users present in the Active User list

**Comment by shubhendusaurabh** [comment] 2015-02-04 06:42
@huangqun not able to reproduce with dev users

**Comment by huangqun** [comment] 2015-02-05 04:41
@shubhendusaurabh I think it's because the dev users don't have so many rows in their profiles.

@skyhit @mdesiderio do you know if there's a way we can add more lines to some test user's profile so we can reproduce this?

**Comment by GSTVAC** [comment] 2015-02-10 21:33
It's fixed now. Probably because ng-scrollbar was replaced by perfect-scrollbar.

To add more lines to the popup open app/js/controllers/baseCtrl.js go to line 306 and replace
```
$scope.coderInfo = data.message;
```
by
```
$scope.coderInfo = data.message + data.message + data.message;
```

**Comment by huangqun** [comment] 2015-02-13 05:30
fixed

**Closed by huangqun** 2015-02-13 05:30 UTC
Labels: fix me

**Comment by huangqun** [comment] 2015-02-13 05:31
credit goes to @GSTVAC because of the extra research on it
